### PR TITLE
PHP 8 Support

### PR DESCRIPTION
**Pull request by driesvints**

### CODE REVIEW

**Comment by driesvints** [comment]
Just like the spatie/url PR this PR can't trigger Github Actions yet until activated. Please be wary to not tag it until the build passes. If you can merge this one so it can trigger the build I can send in a follow-up PR to fix it.

**Comment by drupol** [comment]
How about caching the vendor directory ?

**Comment by driesvints** [comment]
I specifically removed that step because it's not needed anymore with Composer 2. We removed it on all Laravel repos as well.

**Comment by drupol** [comment]
Ho ! How is it possible ? I wasn't aware of that, this is a great news!

Do you have some documentation related to that ?

Thanks!

**Comment by driesvints** [comment]
@drupol Composer 2 is just fast enough these days to make the caching step irrelevant.

**Comment by drupol** [comment]
Ok ok, thanks for explanations.

**Pull request merged**
